version: "3.5"

services:
    anaconda:
        container_name: anaconda_natural_lang_processing
        build:
            context: .
            dockerfile: .\dockerFiles\python\dockerFile
        volumes:
            - ./volumes:/root/python/
        ports:
            - 8888:8888
        restart: always
        